### ISSUE TITLE
Improve error message for form tag and restful controllers

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#108]
_Original author: ipolevoy@gmail.com (July 02, 2012 18:17:09)_

Evan:

I must have been doing something silly. I got unstuck.  One suggestion, as I've run into this a few times when working with rest controllers, especially when migrating a controller to Rest, is to improve the error message to tell you to check if you've specified an &quot;action&quot; parameter on a form or  link_to tag, and to take it off.

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=108_

**Comment by ipolevoy** [comment]
well, t the action parameter is optional;
