### ISSUE TITLE
Upgrade to latest version of FreeMarker

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#133]
_Original author: i...@polevoy.org (May 16, 2013 04:42:52)_

see other dependencies too 

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=133_

**Comment by mppfiles** [comment]
This issue got old.It would be nice to upgrade freemarker again (2.3.20 vs 2.3.28).

**Comment by ipolevoy** [comment]
It is not a big idea to review versions of all dependencies. I will create a new issue for that.
