### ISSUE TITLE
Use StringBuilder

### ISSUE THREAD

**Issue by ericbn** [javalite/activeweb#202]
We know three different JDK classes to do String appending, but there are important differences:

* `StringWriter`: implements `Writer` and delegates to an internal `StringBuffer`. This one should be used as a `Writer` implementation. Having a method that receives a `StringWriter` makes little sense, since if the method needs something to write directly to Strings, not any Writer, it is better to make a contract with any of options below. Plus, you would need to handle IOException in a context where there's really no IO...
* `StringBuffer`: it is thread-safe and doesn't have better performance than the option below.
* `StringBuilder`: straight String appending with no extra toppings.

So my suggestion is we use `StringBuilder` in Templator API.

### References
* http://stackoverflow.com/questions/2980805/string-assembly-by-stringbuilder-vs-stringwriter-and-printwriter
* http://littletutorials.com/2008/07/16/stringbuffer-vs-stringbuilder-performance-comparison/

**Comment by ipolevoy** [comment]
@ericbn , where do we use StringWriter?

**Comment by ericbn** [comment]
Oh, sorry, I should have checked better! It is only in unit tests. The API uses `Writer`. :blush:

**Comment by ipolevoy** [comment]
no problem, you are usually right, so I looked at code up and down! :)
