### ISSUE TITLE
org.javalite.activeweb.Router

### ISSUE THREAD

**Issue by kolshi** [javalite/activeweb#203]
String className = controllerClass.getName();
        if (!className.startsWith("app.controllers")) {
            throw new ControllerException("controller must be in the 'app.controllers' package");
        }
        String packageSuffix = className.substring("app.controllers".length(), className.lastIndexOf("."));

**Comment by kolshi** [comment]
ERROR org.javalite.activeweb.RequestDispatcher - ActiveWeb internal error: 
org.javalite.activeweb.ControllerException: controller must be in the 'app.controllers' package
	at org.javalite.activeweb.Router.getControllerPath(Router.java:323)

**Comment by ipolevoy** [comment]
this is not a bug, but a requirement of the framework. Please, see here: http://javalite.io/controllers#location-of-controllers-in-project
