### ISSUE TITLE
Change Templator format for built-ins

### ISSUE THREAD

**Issue by ipolevoy** [javalite/activeweb#205]
Proposed by Andrey Yanchevsky:

```
${format MM/dd/yyyy article.content}
${esc article.content}
```

also, maybe change the naming of "built-in" to function? :)

**Comment by ipolevoy** [comment]
Also, the BuiltIn API needs to change:

from: 
```
String builtIn.process(String);
```

to:

```
Object builtIn.process(Object);
```

**Comment by ericbn** [comment]
+1 for both Andrey's suggestion and naming "built-in" as function. What about `${escape article.content}`?

**Comment by ipolevoy** [comment]
he is proposing to reverse the order. Currently:

```
${article.content esc}
```
proposal: 

```
${esc article.content}
```

I still think it needs to be called a built-in.

**Comment by ericbn** [comment]
Anything can be "built-in", as it reads more like an adjective...

**Comment by ipolevoy** [comment]
actually, it is a noun as in: "we have an escape built-in"

**Comment by ipolevoy** [comment]
## A few more  proposals:

###  String argument
```
${format "00.##" person.weight}
```
where a "00.##" is a String argument to format built-in

###  Context argument
```
${number format  person.weight}
```
where 'number' is a name of built-in, and 'format' is a name of object in context to use as its argument

**Comment by ipolevoy** [comment]
https://github.com/javalite/activeweb/issues/229
