### ISSUE TITLE
The reverse proxy server redirect Question

### ISSUE THREAD

**Issue by kolshi** [javalite/activeweb#208]
The reverse proxy server : nginx Enable HTTPS Agent to jboss HTTP 
case : post https://yuuji.cn/bookmark  agent to jboss post http://yuuji.cn/bookmark
    @POST
    public void create() {
        bookmarkService.save(param("name"), param("url"), param("icon"));
        redirect();
    }
save After redirect to http://yuuji.cn/bookmark; Expect https://yuuji.cn/bookmark

**Comment by kolshi** [comment]
help @ipolevoy

**Comment by ipolevoy** [comment]
@kolshi, there is nothing ActiveWeb doing that  could break this. Please see this: https://github.com/javalite/activeweb/blob/ccf250dc9d7bedf2036991090f0330349a1d156f/activeweb/src/main/java/org/javalite/activeweb/RedirectResponse.java#L43

For a quick workaround, you can redirect to a fully qualified URL, such as:
```
redirect("https://yuuji.cn/bookmark");
```

**Comment by ipolevoy** [comment]
@kolshi , if you just have a question, please do not create a new issue. Post them to groups: https://groups.google.com/forum/?hl=en#!forum/activeweb

**Comment by kolshi** [comment]
China unable to connect to the Google

**Comment by ipolevoy** [comment]
@kolshi , I feel sorry for you :) this is funny, but not very funny! In any case, try advice above

**Comment by ipolevoy** [comment]
@kolshi, it is OK for you to create issues like this if you have a question, given you have no access to Google.

**Comment by kolshi** [comment]
I use redirectToReferrer to solve the problem!

**Comment by ipolevoy** [comment]
glad it works for you
