### ISSUE TITLE
Review Templator code

### ISSUE THREAD

**Issue by ipolevoy** [javalite/activeweb#210]
Please, review code I have written so far. Please, comment but do not make any changes. It is rough around the edges, but solid structurally and from design point of view. I think it is now time to do some code cleaning . This is still work in progress.

**Comment by ericbn** [comment]
Implemented whole new code under `TemplateParser`.

Supports:

* Non-limited chained identifiers (just first one cannot be a function call):

        foo.list.size()

* Expressions with operators `==`, `>`, `>=`, `<`, `<=`, `!=`, `!`, `||`, `&&`, parenthesis, chained identifiers and single boolean identifiers, like:

        first > second && (first > third || third <= second)
        foo || bar
        foo.list.size() > limit

* Print variable values with `%{...}` (`%` used instead of `$`, because `$` is a valid first character for Java identifiers):

        %{foo.list.size()}

* Tags:
    * `if` with expression:

            <#if (duck.name == name)>...</#if>

        Expression must be enclosed by parenthesis, otherwise parsing would get lost if used with single boolean identifiers:

            <#if foo>bar 

    * `for` with iterable variable (adds `..._index` and `..._has_next` as current implementation):

            <#for user : project.users>
                ...
                %{user_index}
                <#if (user_has_next)>...</#if>
            </#for>

Does not support yet:

* Function calls taking arguments.
* String or numeric constants.
* Customs tags (must change current implementation)

**Comment by ericbn** [comment]
Hi @ipolevoy. I did not use any tool to generate the code. It is pretty self explanatory. It is a recusive descent parser with zero lookahead implemented from the BNF I designed as to have no left recursion and zero lookahead.

There are many tools you can use to implement a Java parser from BNF, but most of them will make you bring dependencies to the project, which I avoided by implementing the parser myself (also given it was not hard and even fun to do :smile:). For a tool, I would recommend you [parboiled](http://parboiled.org).

I also recommend you consider the [Java Template Engine Benchmarker](https://github.com/greenlaw110/template-engine-benchmarks) project to compare performances. This project contains very good template frameworks, missing at least one I would consider too when comparing features and performace: the [Handlebars.java](http://jknack.github.io/handlebars.java/).

**Comment by ipolevoy** [comment]
@ericbn , 

> It is a recusive descent parser with zero lookahead implemented from the BNF I designed as to have >no left recursion and zero lookahead.

as usual, your coding skills are fantastic! I will certainly look into [Java Template Engine Benchmarker ](https://github.com/greenlaw110/template-engine-benchmarks) and run both templators against it.
Also, the  [Handlebars.java](http://jknack.github.io/handlebars.java/) looks interesting, it actually might do. 
The rationale I have for building an internal templating engine is:
* Want to own technology. Defects are fixed fast, easy to integrate things
* Product is developed as needed 
* No dependencies. 
* Better performance
* Syntax as close as FreeMarker as possible 

The last one is a "nice to have", because it is easier with IDEs, and and we are used to its syntax. That said, of all other implementations,  [Handlebars.java](http://jknack.github.io/handlebars.java/) looks the most interesting because it already has a built-in integration.  I wil experiment with it, and potentially benchmark all three (yours, mine and handlebars ) in [Java Template Engine Benchmarker ](https://github.com/greenlaw110/template-engine-benchmarks)  and report results.

**Comment by ipolevoy** [comment]
@ericbn, I did some more benchmarking, and have strange results. I integrated Templator into https://github.com/javalite/template-engine-benchmarks, and when I run the test, Templator performed the worst. When I execute `run.sh` from root, I get FreeMarker at 327ms, and Templator at about 600ms. That looked strange, so I moved the _same exact code_ into a webapp: https://github.com/javalite/templator-benchmark. This project has two branches: `templator` and `freemarker`. Also, there is a JMeter project: https://github.com/javalite/templator-benchmark/blob/freemarker/jmeter.jmx. When I execute 1000 concurrent requests by 100 users using JMeter, the Templator is roughly 40% faster than FreeMarker.  

I know you are skeptical about building a home grown template engine, and I see your point now! I will dig around a bit more though ...

**Comment by ericbn** [comment]
@ipolevoy, looking at your [templator-benchmark](https://github.com/javalite/templator-benchmark) project, my reading there is also that FreeMarker performed better (and remember FreeMarker is slow comparing to most of them :smile:)

[Templator](https://github.com/javalite/templator-benchmark/tree/templator): took 6.837 secs to process 1000 requests, avg. 146.27 requests/sec
[Freemarker](https://github.com/javalite/templator-benchmark/tree/freemarker):  took 4.984 secs to process 1000 requests, avg. 200.65 requests/sec

**Comment by ipolevoy** [comment]
@ericbn, I have exactly opposite results. I get ~ 1600 requests per second on templator, and just under 1000 requests per second on Freemarker. However, I think I'm leaning towards your opinion now, and not sure if I want to continue the templator, or cancel it. I think I underestimated the amount of work to create a templating engine. I do not have a bandwidth to do it now, and potentially the approach is not the fastest. Maybe we need to look at something like this: http://rythmengine.org/ and simply integrate it into ActiveWeb

**Comment by ipolevoy** [comment]
@ericbn , heading your advice, and removing templator. This will be too much work, as you mentioned!
https://github.com/javalite/activeweb/issues/229

**Comment by ericbn** [comment]
@ipolevoy, inspired by this story, I gave this talk: [Introduction to Grammar and Parsing using the Recursive Descent Parser algorithm](https://www.youtube.com/watch?v=9jSSSE2FuLU)

**Comment by ipolevoy** [comment]
@ericbn , this is great. I will take time to learn from you
