### ISSUE TITLE
Android Webview x-requested-with

### ISSUE THREAD

**Issue by jaredmaxwell** [javalite/activeweb#211]
Android's webview in version 4.4+ passes the following header on all requests:
x-requested-with: com.myapp.package

When a request results in a system error the response contains a stacktrace instead of the custom 404 or 500 page in the application.

https://github.com/javalite/activeweb/blob/master/activeweb/src/main/java/org/javalite/activeweb/RequestDispatcher.java#L271

**Comment by ipolevoy** [comment]
@jaredmaxwell  -- Aha!! We had the same issue in current project, and I wondered how this is possible. Thanks for reporting - we will take a look!

**Comment by ipolevoy** [comment]
looks like  this was implemented for: https://github.com/javalite/activeweb/issues/10
However, implementation is not correct, since it checks for presence of the header, and not its value. 

@jaredmaxwell what is the value WebView is sending for this header?   Is this the actual value:

    com.myapp.package

**Comment by jaredmaxwell** [comment]
Whatever the package name of the application that contains the webview.
For example com.rovio.angrybirds for Angry Birds.

Right now the presence of the header is being checked instead of the value XMLHttpRequest.

**Comment by ipolevoy** [comment]
@jaredmaxwell this i fixed, please try a new spanshot: http://repo.javalite.io/org/javalite/activeweb/1.12-SNAPSHOT/

**Comment by jaredmaxwell** [comment]
@ipolevoy Thanks for the quick turnaround!
