### ISSUE TITLE
system/404 view is not returne in native Android 5+ browser

### ISSUE THREAD

**Issue by EgorZhuk** [javalite/activeweb#236]
For some reason default logic for 404 error page doesn't work in native Android 5+ browser. Framework returns stacktrace to user.

**Comment by ipolevoy** [comment]
@EgorZhuk , are you sure your app is properly configured? There is no difference in how it manages different browsers. I just tested native Android app on latest version 5, and it is working just fine inb all browsers, including native. Please, navigate to http://javalite.io/404 to see for yourself.

**Comment by ipolevoy** [comment]
closing as non-issue

**Comment by EgorZhuk** [comment]
I found the cause of the issue in our app.
Android 5 native browser sends 'com.android.browser' in 'X-Requested-With' header.
And here is the code of:
`RequestUtils.isXhr()`

``` java
public static boolean isXhr() {
   return header("X-Requested-With") != null || header("x-requested-with") != null;
}
```

I don't think it's a problem of the framework.

**Comment by ipolevoy** [comment]
excellent!
