### ISSUE TITLE
RequestUtils.isXhr() vs Android "X-Requested-With" header

### ISSUE THREAD

**Issue by odess1t** [javalite/activeweb#237]
Android 5+ native browser sends "X-Requested-With" header set to  'com.android.browser'.
That's why RequestUtils.isXhr() method does not work correctly. 

Similar issue was fixed in terms of https://github.com/javalite/activeweb/issues/211

Is it possible to check the value of the header in xhr() method too?

Thank you!

**Comment by ipolevoy** [comment]
@odess1t, I do not see any reason not to do this. Stay tuned.

**Comment by ipolevoy** [comment]
@odess1t, looks like the current implementation only checks if the header is there and does not check the value: https://github.com/javalite/activeweb/blob/master/activeweb/src/main/java/org/javalite/activeweb/RequestUtils.java#L112

So... it should work, right?

**Comment by odess1t** [comment]
It works for all browsers except of the native Android browser.
If request is initiated by Ajax - the header value is 'XMLHttpRequest'. And RequestUtils.isXhr() works fine.
However native browser sends the same header with value set to "com.android.browser" even if request was NOT initiated by Ajax. Here RequestUtils.isXhr() determines such request as an Ajax call, when in fact it is not.

**Comment by ipolevoy** [comment]
bummer. So, the method needs to check the value and if it IS  "com.android.browser", then it should return false? 
What does this browser sends for standard requests?

**Comment by ipolevoy** [comment]
re-read your comment, is this accurate: 

```
Ajax request: X-Requested-With -> XMLHttpRequest
Standard request: X-Requested-With -> com.android.browser
```
?

**Comment by odess1t** [comment]
Yes, this is correct.

For Ajax requests it sends "XMLHttpRequest" value, as well as other browsers I checked with (Chrome, Firefox).

So, probably the method should return TRUE only in case the header value is 'XMLHttpRequest'.
Please correct me if I'm mistaking and other header values which indicate Ajax request are possible. (Except of "XMLHttpRequest" of course). This would help to avoid checking hardcoded Android-specific value.

**Comment by ipolevoy** [comment]
New snapshot is available: http://repo.javalite.io/ Please, see if it is working so we could close this bug.

**Comment by odess1t** [comment]
Works for me!

Thanks for fixing this!

**Comment by ipolevoy** [comment]
closing
