### ISSUE TITLE
Code adjustment: close stream in finally block

### ISSUE THREAD

**Issue by vyemialyanchyk** [javalite/activeweb#254]
from org.javalite.http.Request:

    public void dispose() {
        //according to this: http://download.oracle.com/javase/1.5.0/docs/guide/net/http-keepalive.html
        //should read all data from connection to make it happy.
        byte[] bytes = new byte[1024];
        try {
            InputStream in = connection.getInputStream();
            if(in != null){
                while ((in.read(bytes)) > 0) {}//do nothing
                in.close();
            }
        } catch (Exception ignore) {
            try {
                InputStream errorStream = connection.getErrorStream();
                if(errorStream != null){
                    while ((errorStream.read(bytes)) > 0) {}//do nothing
                    errorStream.close();
                }
            } catch (IOException ignoreToo) {}
        }
    }

this is more ralaible close (in.read if exception in read the stream remains open, so resource leak):

    public void dispose() {

InputStream in = null;
try {
...
} catch (Exception ex) {
...
} finally {
  IOUtil.closeQuietly(in);
}
}

**Comment by vyemialyanchyk** [comment]
the same should be for errorStream

**Comment by ipolevoy** [comment]
where is IOUtil coming from?

**Comment by vyemialyanchyk** [comment]
org.apache.commons.io.IOUtils is from apache commons, but it does not matter, this is my implementation:

    public static void closeQuietly(Closeable... closeables) {
        for (Closeable closeable : closeables) {
            try {
                if (closeable != null) {
                    closeable.close();
                }
            } catch (IOException ioe) {
                // ignore
            }
        }
    }

**Comment by ipolevoy** [comment]
@vyemialyanchyk , did you see the comment  in code: 

    according to this: http://download.oracle.com/javase/1.5.0/docs/guide/net/http-keepalive.html

**Comment by vyemialyanchyk** [comment]
@ipolevoy , http://docs.oracle.com/javase/1.5.0/docs/guide/net/http-keepalive.html - here is just code snippet, which illustrate the consept, nothing more. Close in finally is more accurate implementation. copy-paste is not good startegy )))

**Comment by ipolevoy** [comment]
Fixed in https://github.com/javalite/activejdbc/issues/467

**Comment by ipolevoy** [comment]
@vyemialyanchyk thanks for suggestion, I user try with resource instead, which made code even cleaner.
