### ISSUE TITLE
Review Request.getInputStream

### ISSUE THREAD

**Issue by vyemialyanchyk** [javalite/activeweb#256]
public InputStream getInputStream() {
        try {
            return connection.getInputStream();
        }catch(SocketTimeoutException e){
            throw new HttpException("Failed URL: " + url +
                    ", waited for: " + connection.getConnectTimeout() + " milliseconds", e);
        }catch (Exception e) {
            throw new HttpException("Failed URL: " + url, e);
        }
    }

===>

    public InputStream getInputStream() {
        try {
            return new ByteArrayInputStream(bytes());
        }catch(SocketTimeoutException e){
            throw new HttpException("Failed URL: " + url +
                    ", waited for: " + connection.getConnectTimeout() + " milliseconds", e);
        }catch (Exception e) {
            throw new HttpException("Failed URL: " + url, e);
        }
    }

please take a look my version, I do not sure but it looks better in sense of close connection input stream. For ByteArrayInputStream nothing to close in sense of resources.

**Comment by vyemialyanchyk** [comment]
may be there is a sense to have both functions... getSafeInputStream() - a name for second one.

**Comment by vyemialyanchyk** [comment]
this is from javalite.common. is it a right place for javalite.common issues?

**Comment by ipolevoy** [comment]
@vyemialyanchyk , JavaLite common is part of ActiveJDBC: https://github.com/javalite/activejdbc/tree/master/javalite-common

However, later this year we want to aggregate all code under the same roof. 

What class are you referring to?

**Comment by vyemialyanchyk** [comment]
org.javalite.http.Request

**Comment by ipolevoy** [comment]
yeah, found it

**Comment by ipolevoy** [comment]
this would be a bad idea. Imagine you are downloading a 500mb file. The entire thing will load im heap with your solution.

**Comment by vyemialyanchyk** [comment]
some developers do not understand the intention of this method and necessity to close streams. 
I understand your point (take a look getSafeInputStream comment), so my proposition is to have 2 versions of the method. This would help some devs to select correct one.

**Comment by ipolevoy** [comment]
@vyemialyanchyk a second method with the same functionality will ado to confusion: https://en.wikipedia.org/wiki/Single_responsibility_principle

**Comment by vyemialyanchyk** [comment]
@ipolevoy there is no contradiction to this principle here. getSafeInputStream - may be this is not a good name. I would prefere to have simple function, which will not requied to call close for InputStream (like getSafeInputStream). Telling a truth, here is a bad desing to return object, which require to call close to free resources. I think initial version of Request.getInputStream violate 'Single responsibility principle'... org.javalite.http.Request should be responcible to close the stream. But I do not sure is a sense here to add complication here, like

public processInputStream(IInputStreamProcessor isp) {
...
InputStream is = connection.getInputStream()
...
isp.process(is);
...
is.close();
...
}

instead of getInputStream.

I think comment for getInputStream, what in this case developer resposible to close stream would be enough, I insist the comment necessity because I see how people simply forget to close streams. getSafeInputStream - here as just like comment replacement.

**Comment by ipolevoy** [comment]
@vyemialyanchyk , I see your arguments, bit do not see how this can be improved, other than implementing some sort of listener pattern, similar to: http://javalite.github.io/activejdbc/org/javalite/activejdbc/Base.html#find(java.lang.String, org.javalite.activejdbc.RowListener). 

Alternatively, we can improve documentation.

**Comment by ipolevoy** [comment]
if no one interested. I will close this soon
