### ISSUE TITLE
DB.find ==> IllegalArgumentException("query must be 'select' query")

### ISSUE THREAD

**Issue by vyemialyanchyk** [javalite/activeweb#278]
org.javalite.activejdbc.DB.find:
`if(!SELECT_PATTERN.matcher(query).find()) { throw new IllegalArgumentException("query must be 'select' query"); }`

SELECT_PATTERN is wrong, with upgrade to 1.4.11 all queries like:

`(select distinct(abc) from bcd) intersect (select distinct(abc) from cbd)`

stops work correctly.

**Comment by ipolevoy** [comment]
@vyemialyanchyk you are right, we just need to remove this test.

**Comment by ipolevoy** [comment]
@vyemialyanchyk fixed in https://github.com/javalite/activejdbc/issues/483

**Comment by ipolevoy** [comment]
Please, try a snapshot: http://repo.javalite.io
