### ISSUE TITLE
Managing two connections to two oracle schemas with same structure but different content

### ISSUE THREAD

**Issue by jaysea57** [javalite/activeweb#284]
Hi,
I need to make it such that some controllers point to one schema and others controllers to another schema which is identical in structure, without having to duplicate the Model classes.

I have found the solution described below, which is working, but I need expert advice on whether it is thread safe in a high volume environment.

What I did is:

- Defined 2 connection pools in Tomcat with 2 jndi names:
  - "java:/comp/env/jdbc/magic_dev"
  - "java:/comp/env/jdbc/magic_dev_pm"

- Defined two environments in DBConfig (my extension of AbstractDBConfig):
 - environment("development").jndi("java:/comp/env/jdbc/magic_dev");
 - environment("development_pm").jndi("java:/comp/env/jdbc/magic_dev_pm");

- Defined my own DBConnectionFilter which is a copy of the same, except for the fact that it invokes Configuration.getConnectionSpecWrappers with the environment parameter as opposed to an empty parameter list. The filter class is called ByGameConnectionFilter:

- ByGameConnectionFilter Constructor:
   ```java
    public ByGameConnectionFilter(String envName) {
        this.envName = Configuration.getEnv() + "_" + envName;
    	log.debug("Constructor ByGameConnectionFilter envName: " + this.envName);
    }
   ```

- Invocation of getConnectionWrappers (differs from DBConnectionFilter on line 2):

   ```java
    private List<ConnectionSpecWrapper> getConnectionWrappers() {
        List<ConnectionSpecWrapper> allConnections =  Configuration.getConnectionSpecWrappers(this.envName);  // this differs from standard DBConnectionFilter because it uses the parameter this.envName set in the constructor
        List<ConnectionSpecWrapper> result = new LinkedList<ConnectionSpecWrapper>();
        for (ConnectionSpecWrapper connectionWrapper : allConnections) {
            if (!connectionWrapper.isTesting() && (dbName == null || dbName.equals(connectionWrapper.getDbName())))
                result.add(connectionWrapper);
        }
        return result;
    }
    ```
In the AppControllerConfig class, I associate two different filters, depending on the controller:

       ```java
       // standard schema pointing to "magic_dev" jndi name:
        ByGameConnectionFilter db = new ByGameConnectionFilter();
        add(db)
            .to(app.controllers.HomeController.class)
            .to(app.controllers.priv.admin.AltriController.class)
            .etc...

        // pm schema pointing to "magic_dev_pm" jndi name:
        ByGameConnectionFilter dbcdg = new ByGameConnectionFilter("pm");
        add(dbcdg)
            .to(app.controllers.pub.pm.AccediController.class)
        	.to(app.controllers.pub.pm.MainController.class)
        	.to(app.controllers.priv.pm.ClienteController.class)
        	;
   ```

This appears to work ok, but I am concerned about the fact that the two Filters will be sharing, (I believe), the table metadata (among other things). Now, the metadata is identical in the two schemas, so it may be alright, but I am not sure. This is where I need an expert to validate the solution.

**Comment by ipolevoy** [comment]
I think you are confusing what an environment is. While your solution will work, it is a bit hacky. 
In ActiveWeb, the DbConfig and DBCOnnectionFilter work in tandem. However, since you wrote your own filter, you can break dependency on DbConfig. For instance, your implementation of the filter can be as simple as: 

```java
public class ByGameConnectionFilter extends ControllerFilterAdapter {
    private String jndi;
    public ByGameConnectionFilter(String jndi) {
        this.jndi = jndi;
    }

    public void before() {
        Base.open(jndi);
    }

    public void after() {
        Base.close();
    }
}
```

When attaching the filter, provide JNDI connection name in `AppControllerConfig`: 

```java
add(new ByGameConnectionFilter("java:/comp/env/jdbc/magic_dev"))
     .to(HomeController.class, AltriController.class); // note: this is a vararg!


add(new ByGameConnectionFilter("java:/comp/env/jdbc/magic_dev_pm"))
        .to(AccediController.class, MainController.class, ClienteController.class);
```

The `DBConfig` in this case will simply be empty or missing. 

Onto your question about metadata. ActiveJDBC does maintain only one schema in memory. This means that if you are going to different databases at runtime, their schemas need to be the identical. This is more concerning setting values to attributes: 

```java
person.set("name", "John");
```
This will break if the table `PEOPLE` does not have the column `name`. If both of your databases have the same structure, you have nothing to worry about. ActiveJDBC will extract the schema from the database it connects to first, and then will use it for the rest of runtime. 

So.. the models find a connection corresponding to the logical DB name on current thread. In all honesty, they absolutely do not care where that connection is pointed, as long as queries generated by models do not cause SQL errors. In your case that  will not be a problem, because your schemas are the same. 

> Filters are executed  by [AppIntegrationSpec](http://javalite.io/testing#appintegrationspec---bootstraps-controllerfilters-into-test).  

This means that if you write your own subclass of `AppIntegrationSpec`, your custom filter will be executed during the build - something you do not want. This can be easily fixed in the framework: https://github.com/javalite/activeweb/issues/285


I hope it helps,

**Comment by jaysea57** [comment]
Hi Igor,

yes it definitely helps, thanks for the clear explanation, and the concise solution. If you say that I can break the dependency on DBConfig, then I will go for the solution you have described. My hacked solution was partly due to the fact that, not knowing activeJdbc under the hood, I did not dare to think I could forgo the DBConfig part of it.

Another worry was that the single instance of metadata might in some way play up with two instances of the connection wrappers, so its comforting to hear your opinion on it.

That leaves me with one small problem, the fact that, in production, the jndi names are magic_prod and magic_prod_pm, as opposed to magic_dev and magic_dev_pm, but I can put the relevant jndi names in development.properties and production.properties (which are read as $ACTIVE_ENV.properties).

I'm afraid I did not understand your last paragraph about AppIntegrationSpec.. I don't use testing scripts.. I just test the app manually. Do you think I need to do something on that?

Thanks again

**Comment by ipolevoy** [comment]
if you do not write tests, than you do not have to worry about AppIntegrationSpec. However,  you know ...  not having tests is baaaaad ;)

For your configuration in different environments, you can use our library called AppConfig: https://github.com/javalite/activejdbc/tree/master/app-config

All you need then is: 

* Create as many property files as the number of environments you have: development.properties, production.properties, etc. 
* Set `ACTIVE_ENV` in each environment accordingly. You do not need to do this in development, as the framework defaults to "development" if ACTIVE_ENV is not provided. 
* Add properties: 

development.properties file:
```
magic=java:/comp/env/jdbc/magic_dev
magic_pm=java:/comp/env/jdbc/magic_dev_pm
```

production.properties file:
```
magic=java:/comp/env/jdbc/magic_prod
magic_pm=java:/comp/env/jdbc/magic_prod_pm
```

Then, bind filters  like this: 

```java
import static org.javalite.app_configAppConfig.p;
... 

add(new ByGameConnectionFilter(p("magic")))
     .to(HomeController.class, AltriController.class); // note: this is a vararg!


add(new ByGameConnectionFilter(p("magic_pm")))
        .to(AccediController.class, MainController.class, ClienteController.class);
```

The `AppConfig` will pull the right property from the right file based on environment. 

-----

Alternatively, you can just standardize on jndi names in all your environments: 

```
java:/comp/env/jdbc/magic
java:/comp/env/jdbc/magic_pm
```

Either method will work, but you will benefit from `AppConfig` in the long run.

**Comment by ipolevoy** [comment]
@jaysea57 since  this is not a real issue, I will close it. You can continue to comment here if you  have more questions.

**Comment by jaysea57** [comment]
Hi Igor,
yes, I just test the app functionally, I'm a very naughty boy!  ;)
Thanks for everything, all my issues are sorted!
Regards
J

**Comment by ipolevoy** [comment]
@jaysea57 excellent!
