### ISSUE TITLE
Implement OPTIONS method for RESTful controllers

### ISSUE THREAD

**Issue by ipolevoy** [javalite/activeweb#306]
The idea is to route them directly to a specific action. The best action name to route to seems to be 'options'. 

This means that the request like this: 

```
OPTIONS /hello
```

will be routed to `HelloController#options` action.

**Comment by cunux** [comment]
As this is a generic in nature, which needs to respond with a status 200. This can be sent directly from the framework instead of having to route to a specific controller method.

`OPTIONS /*`

Any request with options will return a success to the browser subsequent to which browser will make the actual request of delete or put.

**Comment by ipolevoy** [comment]
@cunux as far as I understand, the response to an OPTTIONS request  will return some headers indicating what options this end-point supports. As such, giving the power  to a developer to respond with whatever options he/she needs. Please see: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing#Response_headers
As you can see, there are many headers you can set on the response. Doing it in a controller makes sense. 

Thoughts?

**Comment by ipolevoy** [comment]
@cunux I will proceed to implement as described above. You will have a full control of whatever headers you want to set.

**Comment by cunux** [comment]
Sorry about the time delay, timezone issues. I think routing to a single method will work fine. Another observation was that in a regular controller using OPTIONS and DELETE annotation makes a delete request work fine.

```java
@OPTIONS
@DELETE
public void delete(){
...
}
```

The same code above in a RESTful controller does not work. Is this something that can be fixed in the framework?

**Comment by ipolevoy** [comment]
@cunux, in a regular  controller  you can do anything you want. In contrast, the RESTful controllers have a pre-set routing rules. This is why it "does not work". In other words, RESTful controllers do not use annotations, they use a set of rules to go by.

**Comment by cunux** [comment]
Makes sense. Please proceed with your solution,

**Comment by ipolevoy** [comment]
@cunux already done. Please try snapshot: http://repo.javalite.io/org/javalite/activeweb/1.14-SNAPSHOT/

**Comment by ipolevoy** [comment]
@cunux have  you tried this?

**Comment by GehadFathy** [comment]
I'm working with activeweb 1.15 and restful controller but options method doesn't work with path parameters ,it gives this error : 
Failed to map resource to URI: /rule/3 where rule is my controller and 3 is the id  
it only work without parameters

**Comment by nsiniakevich** [comment]
@ipolevoy I have the same issue as @GehadFathy described on 2.2 version

as I can see from [Router](https://github.com/javalite/activeweb/blob/master/activeweb/src/main/java/org/javalite/activeweb/Router.java) class:

```
        //OPTIONS 	/photos/            options
        if (parts.length == 0 && method.equals(HttpMethod.OPTIONS)) {
            return new Route(controller, "options", method);
        }
```

it has check `parts.length == 0`, but when id is provided in URI, when `parts.length` is 1.

As workaround, I've tried to create custom route, but [RouteBuilder](https://github.com/javalite/activeweb/blob/master/activeweb/src/main/java/org/javalite/activeweb/RouteBuilder.java) doesn't have `options()` method. So it didn't work.

**Comment by ipolevoy** [comment]
@nsiniakevich can you please provide an example of the URI you are trying as well as the controller and response you are expecting - I want to reproduce your case

**Comment by nsiniakevich** [comment]
@ipolevoy 

Request looks like: `OPTIONS /orders/:id`

I'm using [httpie](https://github.com/jakubroztocil/httpie) tool to perform requests

`http OPTIONS http://localhost:8080/orders/1`

Actual response

```
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Date: Mon, 03 Dec 2018 09:03:16 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.22.v20170606)
Transfer-Encoding: chunked

{
    "code": 404,
    "message": "Resource Not Found"
}
``` 

logs:

```
2018-12-03 12.01.04:182 [qtp407997647-18] WARN org.javalite.activeweb.Router - Failed to find action for request: /orders/1
2018-12-03 12.01.04:182 [qtp407997647-18] ERROR org.javalite.activeweb.Router - Failed to recognize URL: '/orders/1'
2018-12-03 12.01.04:183 [qtp407997647-18] INFO org.javalite.activeweb.RequestDispatcher - {"controller":"","duration_millis":1,"remote_ip":"0:0:0:0:0:0:0:1","method":"OPTIONS","action":"","error":"Failed to map resource to URI: /orders/1","url":"http://localhost:8080/orders/1","status":404}
2018-12-03 12.01.04:183 [qtp407997647-18] INFO org.javalite.activeweb.freemarker.FreeMarkerTemplateManager - Rendering template: '/system/404.ftl' with layout: '/layouts/default_layout.ftl'. 
```

Excepted response:

```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
Content-Type: application/json; charset=UTF-8
Date: Mon, 03 Dec 2018 09:03:21 GMT
Server: Jetty(9.2.22.v20170606)
Transfer-Encoding: chunked
```

The same response I got when on request without `:id` `http OPTIONS http://localhost:8080/orders`

**Comment by nsiniakevich** [comment]
@ipolevoy do you need any additional information from my side?

**Comment by ipolevoy** [comment]
No, I think this is sufficient, just super busy at the end of the year

**Comment by jacktang** [comment]
How to response `OPTIONS` so that chrome will auto send `POST` request to remote?

**Comment by jacktang** [comment]
Well, I got it. BTW: how about add `options()` and `method(x)` to `RouteBuilder` so that we can map the HTTP method to the corresponding action.

**Comment by ipolevoy** [comment]
@jacktang , here is the implementation for custom routes: 
https://github.com/javalite/activeweb/issues/419

**Comment by ipolevoy** [comment]
@GehadFathy  and @nsiniakevich I pushed a new commit with the fix for this issue. Please, wait 30 minutes before trying out the 2.3-SNAPSHOT.
