### ISSUE TITLE
[Question] Hot deployment 

### ISSUE THREAD

**Issue by robertoestivill** [javalite/activeweb#307]
Hi guys,
I was wondering how activeweb implemented hot deployment (https://www.youtube.com/watch?v=YX1TAtuSqQE) or if it is a Jetty functionality that activeweb just configures.
Is there any class or reference I could take a look?
Thanks

**Comment by ipolevoy** [comment]
ActiveWeb does not implement hot deployment. In the development environment, it uses a Jetty plugin to run directly from sources. Here is one of the examples: https://github.com/javalite/activeweb-bootstrap/blob/master/pom.xml#L39. 

Here: http://javalite.io/structure_of_activeweb_project#location-of-controllers it says: "_Controllers are compiled on the fly and reloaded on every request in development mode._"

In  other words, the app is not re-deployed, but controller classes are recompiled and re-loaded on every request in development environment only. No other Java code is reloaded, just controllers. This allows you to play with Java code in controllers for fast prototyping. 

This is achieved by a custom class loader: https://github.com/javalite/activeweb/blob/master/activeweb/src/main/java/org/javalite/activeweb/DynamicClassLoader.java

This class will call a compiler on the Java  file representing a current controller. The resulting byte code is then loaded to process a single request.

**Comment by robertoestivill** [comment]
Awesome! I will take a look.
Thanks for taking the time to explain.

**Comment by ipolevoy** [comment]
@robertoestivill I forgot to mention this flag: https://github.com/javalite/activeweb-bootstrap/blob/master/pom.xml#L46
If turned on, it will reload controllers, otherwise it will not.
