### ISSUE TITLE
Add support for container-based authentication (isUserInRole())

### ISSUE THREAD

**Issue by mppfiles** [javalite/activeweb#310]
Hi guys,
we are using [container-based authentication in Tomcat](https://tomcat.apache.org/tomcat-7.0-doc/config/realm.html) using a JDBCRealm, we authenticate and manage our users with another -legacy, servlet based- apps and I'm wondering how I can access isUserInRole() method from HttpServletRequest (available in HttpSupport), since this class is hidden from controllers.
Moreover, we cannot obtain the list of roles assigned to a user because:
- we don't have access to the realm (user database and roles) from the app due to permissions.
- Tomcat (and the Servlet spec) lacks of some method like user.getRoles().

So I have no other way but ask for the role to the container with isUserInRole().
It would be OK to add a proxy method, for example, in HttpSupport? If you agree, I can submit a PR.

Thanks!

**Comment by ipolevoy** [comment]
@mppfiles it should be possible to do this from a filter. Let me see.

**Comment by ipolevoy** [comment]
@mppfiles this is done, you can  access to HttpServletRequest: https://github.com/javalite/activeweb/blob/master/activeweb/src/main/java/org/javalite/activeweb/HttpSupport.java#L642

Here is an example  of a secure app you might want  to see: 
https://github.com/javalite/activeweb-secure

The login is done here: 
https://github.com/javalite/activeweb-secure/blob/master/src/main/java/app/controllers/LoginController.java

and the check for a session is in the filter:
https://github.com/javalite/activeweb-secure/blob/master/src/main/java/app/controllers/authorization/AuthorizationFilter.java#L17
it should be easy for you to replace login in the LoginController

**Comment by mppfiles** [comment]
This is freakin' great, thanks @ipolevoy ! Switching to master until you release this to Maven.

**Comment by ipolevoy** [comment]
@mppfiles , haha enjoy. How did you discover AW?

**Comment by mppfiles** [comment]
Found ActiveJDBC first, googling sort of "java-orm-activerecord". Then found AW, and decided to try it. Both projects are great!

**Comment by ipolevoy** [comment]
@mppfiles thanks,  enjoy

**Comment by mppfiles** [comment]
@ipolevoy please, release a new version in Maven with this change whenever possible.
It would help a lot adopting this tool in corporate environments.
Thanks a lot!

**Comment by ipolevoy** [comment]
@mppfiles , we will release in the next few days, stay tuned!

**Comment by ipolevoy** [comment]
@mppfiles both ActiveJDBC and ActiveWeb have been released!

http://javalite.io/activejdbc-release-notes-december-22-2016
http://javalite.io/activeweb-release-notes-december-24-2016

In the future, we are unifying the versions of both to 2.X. 

Enjoy!
