### ISSUE TITLE
Handling multiple requests at the same time

### ISSUE THREAD

**Issue by halileohalilei** [javalite/activeweb#324]
I'm not sure if this is caused by ActiveWeb or if it qualifies as an issue. I've been using JavaLite for a couple of months now and I have a server up and running on Azure. Now I'm writing another Java application which needs to send multiple requests to this server concurrently. I wrote about it on [this SO post](http://stackoverflow.com/questions/42045251/sending-queries-in-parallel-with-executorservice-in-java-8). 

Let's say a single request takes **t** time on my ActiveWeb server and I'm sending **n** (which is the number of threads on my client) requests from my client application in parallel. What happens is, all **n** requests get a response in **n * t** time, instead of around **t**.  If I send more than **n** requests, than the first **n** requests are handled in the previous manner, however the remaining requests are handled without any problems.

I have no idea why this is happening, but I'm guessing it's somewhat related to the way ActiveWeb handles multiple requests at the same time. Please tell me if I'm wrong.

**Comment by ipolevoy** [comment]
@halileohalilei there is absolutely nothing special in ActiveWeb processing requests. ActiveWeb  is a Servlet framework and  processes requests asynchronously, like any other servlet. We implemented a ton of commercial projects and certainly stressed ActiveWeb with multiple threads while not observing what you are describing. Just see this: https://www.techempower.com/benchmarks/#section=data-r13&hw=ph&test=json. If your app processes requests in **n * t** time, you need to look for instances of synchronization in your app.

**Comment by halileohalilei** [comment]
@ipolevoy You're right. I've just messed with both the server and client code and it seems something's wrong with the way async tasks are being gathered in my client app, not the way the requests are handled. I'm closing the issue, sorry for taking your time and thank you for the quick response.
