### ISSUE TITLE
Logger in org.javalite.activeweb.RequestDispatcher should Optionally include some or all headers

### ISSUE THREAD

**Issue by tjennings** [javalite/activeweb#338]
Proposed Example: 

public class AppBootstrap extends Bootstrap {
    public void init(AppContext context) {
        Configuration.logHeaders(true); //Log all headers
        Configuration.logHeaders("x_header_1", "x_header_2"); //selected headers
    } 
   ...
}

{"level":"INFO","timestamp":"Wed Apr 05 14:51:08 CDT 2017","thread":"catalina-exec-15","logger":"org.javalite.activeweb.RequestDispatcher","message":{"controller":"app.controllers.NavigationMapsController","action":"save","duration_millis":17,"method":"POST","status":200, "headers": {"x_header_1": "value", "x_header_2":"value"}}

**Comment by ipolevoy** [comment]
@tjennings where do you think it is best to configure what headers you want? Maybe in web.xml: 



    <filter>
        <filter-name>dispatcher</filter-name>
        <filter-class>org.javalite.activeweb.RequestDispatcher</filter-class>
        <init-param>
            <param-name>exclusions</param-name>
            <param-value>images,js,css,fonts,ico,png,jpeg,jpg,otf,ttf,svg,eot,woff</param-value>
        </init-param>
        <init-param>
            <param-name>root_controller</param-name>
            <param-value>home</param-value>
        </init-param>
        <init-param>
            <param-name>encoding</param-name>
            <param-value>UTF-8</param-value>
        </init-param>
        <init-param>
            <param-name>log_headers</param-name>
            <param-value>User-Agent,Content-type</param-value>
        </init-param>
    </filter>


Not too happy with config name `log_headers`.

**Comment by ipolevoy** [comment]
@tjennings we might also provide wild card  to log all headers: *

**Comment by ipolevoy** [comment]
fixed in https://github.com/javalite/activeweb/issues/385
