### ISSUE TITLE
Add datasource to ConnectionBuilder

### ISSUE THREAD

**Issue by alniks** [javalite/activeweb#340]
It relates to https://github.com/javalite/activejdbc/issues/589. We need a corresponding method in org.javalite.activeweb.ConnectionBuilder:

```
    /**
     * Provide a datasource configured for runtime.
     * @param dataSource datasource 
     */
    public void dataSource(DataSource dataSource) {
        connectionWrapper.setConnectionSpec(new ConnectionDataSourceSpec(dataSource));
    }
```

**Comment by ipolevoy** [comment]
@alniks in what class, and for what purpose?

**Comment by alniks** [comment]
To https://github.com/javalite/activeweb/blob/master/activeweb/src/main/java/org/javalite/activeweb/ConnectionBuilder.java so it could be used for obtaining connections from the DataSource in web applications.
