### ISSUE TITLE
CSRF filter.

### ISSUE THREAD

**Issue by devMls** [javalite/activeweb#362]
Is possible create a built-in framework CSRF protection filter?

**Comment by ipolevoy** [comment]
@devMls please explain in more detail what you mean. There are many flavors of CSRF attacks.

**Comment by devMls** [comment]
Hi, i am nota expert but some frameworks offer a filter foro csef protección maybe playframework can be a good example

Note: As of Play 2.6.x, the CSRF filter is included in Play’s list of default filters that are applied automatically to projects. See the Filters page for more information.

Play provides a global CSRF filter that can be applied to all requests. This is the simplest way to add CSRF protection to an application. To add the filter manually, add it to application.conf:

play.filters.enabled += play.filters.csrf.CsrfFilter
It is also possible to disable the CSRF filter for a specific route in the routes file. To do this, add the nocsrf modifier tag before your route:

**Comment by ipolevoy** [comment]
@yanchevsky can you please explore this?

**Comment by ipolevoy** [comment]
this was implemented, but unfortunately committed to another issue: https://github.com/javalite/activeweb/issues/316

so, closing this issue as already implemented. If you want to protect your forms with CSRF, all you have to do is add the `CSRTFilter` in your `AppControllerConfig` class. You may want  to exclude it from some specific routes.
