### ISSUE TITLE
list action in restful controllers

### ISSUE THREAD

**Issue by devMls** [javalite/activeweb#372]
Usually I find in this controllers the necesity of implement a html list of objects, like index but no json in html way.

what do you think?

**Comment by ipolevoy** [comment]
Not sure I follow your question. You can use ActiveWeb to build dynamic sites or rest services, up to you.

**Comment by ipolevoy** [comment]
@devMls I will be closing this issue for lack of interest if you do not offer any more comments.

**Comment by ipolevoy** [comment]
closing due to a lack of interest
