### ISSUE TITLE
can't find Dbconfg class ,but under "activejdbc 1.4.11 and activeweb 1.3" no problem .

### ISSUE THREAD

**Issue by jessfou** [javalite/activeweb#380]
under " activejdbc version is 1.4.13  and activeweb version is 1.5  " environment ,throws exception javalite.activeweb.InitException: There are no connection specs in 'development' environment, i checked ths console log ，the reason is can't find Dbconfg class ,but under "activejdbc 1.4.11 and activeweb 1.3" no problem .
Thanks,Hope reply!

**Comment by ipolevoy** [comment]
@jessfou sorry just saw this. Do not mix different versions of the same framework. 
Use the latest releases together: 
http://javalite.io/activejdbc#releases
http://javalite.io/activeweb_releases
