### ISSUE TITLE
Change log level to ERROR and throw exception if AppConfig fails to initialize

### ISSUE THREAD

**Issue by mikeebert** [javalite/activeweb#386]
When the `RequestDispatcher` initializes the application [it may only log a warning when it fails to initialize the `AppConfig`](https://github.com/javalite/activeweb/blob/9c912e89a20576de6822b87ab6a435d81f4f1339/activeweb/src/main/java/org/javalite/activeweb/RequestDispatcher.java#L129).

More often than not it seems that failing to initialize the `AppConfig` will create an error that prevents any web application that uses the `RequestDispatcher` from successfully running. 

I recommend changing the log level to ERROR and throwing an exception that prevents the application from successfully starting.

**Comment by ipolevoy** [comment]
@mikeebert failing to load `AppConfig` will result to default values for that type of a config. Failing to load `AppBootstrap` will  prevent the app from running. Basically if `AppBootstrap`  failed to `init()`, the app failed to deploy and thus will not run.

**Comment by mikeebert** [comment]
Thanks for the explanation and the quick update to the log level. Where would we catch this `InitException` to alert us that the app did not fail to start?

**Comment by ipolevoy** [comment]
A container should dump it into its log file
