### ISSUE TITLE
Change ControllerFilter.onException(Exception) to Change ControllerFilter.onThrowable(Throwable)

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#40]
_Original author: ipolevoy@gmail.com (June 06, 2011 20:13:02)_

this is to allow to catch more runtime problems thank with just exceptions

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=40_

**Comment by ipolevoy** [comment]
rejecting, too easy to break dependencies

**Comment by ipolevoy** [comment]
RequestDispatcher will catch Trowablew anyway
