### ISSUE TITLE
Handling XSS in views

### ISSUE THREAD

**Issue by mppfiles** [javalite/activeweb#416]
I didn't found any place in docs mentioning how to deal with XSS attacks.
Currently, it's easy to perform such attack using [the example in docs](http://javalite.io/context-parameters) of displaying request parameters in views. 

````freemarker
Your name is: ${request.name}. 
````

At least, the docs should mention how to prevent such attacks using the [freemarker built-in feature](https://freemarker.apache.org/docs/ref_directive_escape.html):
````freemarker
Your name is: ${request.name?html}. 
````

Please note that this method is currently deprecated, it's important to state that currently the framework is using an old version of freemarker (see #133).
Upgrading freemarker in pom.xml is easy, if anyone is interested:

`pom.xml`
````xml
<dependency>
    <groupId>org.freemarker</groupId>
    <artifactId>freemarker</artifactId>
    <version>2.3.28</version>
</dependency>
````

And to set html output escaping by default (requires freemarker 2.3.24+):

`app.config.FreeMarkerConfig.java`
````java
//...
public void init() {
  //...
   getConfiguration().setOutputFormat(HTMLOutputFormat.INSTANCE);
}
````

`WEB-INF/views/layouts/default.ftl`
````freemarker
${page_content?no_esc}
````

With this method, the framework will be secure by default: it performs auto-escaping by default, as well as [many](https://guides.rubyonrails.org/security.html#html-javascript-injection-countermeasures) [other](https://laravel.com/docs/5.7/blade#displaying-data) [frameworks](https://docs.djangoproject.com/en/2.1/topics/security/#cross-site-scripting-xss-protection).
Of course this can be overrided as per [FreeMarker docs](https://freemarker.apache.org/docs/dgui_misc_autoescaping.html#dgui_misc_autoescaping_disableautoesc). For example, for json templates:

````freemarker
<#ftl output_format="JSON">
````

Hope this helps!

**Comment by ipolevoy** [comment]
@mppfiles , this is a good advice for people. The framework provides a method [sanitize(string)](http://javalite.github.io/activeweb/snapshot/org/javalite/activeweb/HttpSupport.html#sanitize-java.lang.String-), so you can write this in  your controller: 

```java
String name = sanitize(param("name"));
```

This is a method of protecting against garbage users may paste in. We have religiously used this method of protection across all our projects and it has served us well. 

I will start writing a JavaLite book: https://github.com/javalite/book, and this issue might be used as  a chapter. 

I will create a new issue to revisit all dependencies and upgrade as appropriate.

Closing this  issue, but we can still talk here.

**Comment by mppfiles** [comment]
Thank you for your advice. I was tempted to use such method in controllers, but I wanted something more transparent, out-of-the-box solution.

Of course, the input must be validated and filtered, I already do that with custom internal clases. But output escaping is a separate issue: it's only relevant in certain "execution contexts". For example: I can save a snippet of html code in a text field on my database with no problems at all. But, the problem arises exclusively when this value is evaluated in... say, an HTML view (maybe JSON too...).

Remember, this is a full-stack, opinionated framework. IMO, as such, it must be secure by default, with the possibility of deactivate such protections on demand. 
More on the same line: I'm looking at you, #362 ;) .

A book is a great idea! I will try to collaborate on it if you don't mind!

**Comment by ipolevoy** [comment]
@mppfiles I hear you - first, thanks for extending a helping hand for the book all help is much appreciated. I will create a TOC for the book in the next few days. 
When building a framework, one should be cognizant of the backwards compatibility. As such, enabling something my default, especially on the global level may break  systems that depend on it. However, I will certainly think through  yours and @devMls's recommendations. Need to research more on this topic.

**Comment by mppfiles** [comment]
so, @ipolevoy , any news regarding the book? :smile:

**Comment by ipolevoy** [comment]
@mppfiles ,  this  got delayed (obviously) due my company being acquired and other personal changes. However, I wil attempt to carve out at least some time  every day to write a bit. Just pushed the initial toc - not much to look at, but will  bring it to a decent state tomorrow
