### ISSUE TITLE
Develop statistics collection for requests

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#42]
_Original author: ipolevoy@gmail.com (June 15, 2011 16:43:39)_

this can be implemented similarly to statistics collection in ActiveJDBC.

Can be done as a global filter: StatisticsFilter 

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=42_

**Comment by ipolevoy** [comment]
done a long time ago, see http://javalite.io/statistics_reporting
