### ISSUE TITLE
Implement simulation of remote IP, host and port in controller specs

### ISSUE THREAD

**Issue by yanchevsky** [javalite/activeweb#421]
How to simulate remote requests in specs?
Something like:
request().**from("address","host","port")**.get("...")
or
request().**from("address")**.get("...")
```
public RequestBuilder from(String... from) {
....
}
```

**Comment by ipolevoy** [comment]
@yanchevsky I implementer the remote IP address mocking. For host and port, you can just use corresponding headers. See these methods for hints: https://github.com/javalite/activeweb/blob/717731cb3c070aad06de9054af67307294d5b203/activeweb/src/main/java/org/javalite/activeweb/RequestUtils.java#L206

They are available in controllers
