### ISSUE TITLE
activeweb.properties not working!

### ISSUE THREAD

**Issue by yanchevsky** [javalite/activeweb#425]
Router cannot recognize correct controller name.
If we change **rootPackage** in **activeweb.properties** then we will receive this exception in any case:
```
org.javalite.activeweb.ControllerException: controller must be in the 'app.controllers' package
	at org.javalite.activeweb.Router.getControllerPath(Router.java:371)
	at org.javalite.activeweb.AppController.render(AppController.java:65)

```

**Comment by ipolevoy** [comment]
this feature is not even advertized. I'm of the opinion that this should not be fixed.

**Comment by ipolevoy** [comment]
Please, see http://javalite.io/structure_of_activeweb_project#location-of-controllers - `app.controllers`  is the required package.

**Comment by ipolevoy** [comment]
will not fix, the controller package is too important and routing is tied to it,.
