### ISSUE TITLE
activeweb javalite controller not found on server

### ISSUE THREAD

**Issue by juanep1711** [javalite/activeweb#432]
Hello, this is my first time using javalite, i have been watching the documentation, the problem is that i have created the model Person and its controller People and index file but when i run it on the server i get the error "404 not found", could someone help me, i have followed the steps of this video https://www.youtube.com/watch?v=wajjyZlFWEM so i don´t know what could be the prolem, btw i´m using maven, eclipse and tomcat as server

**Comment by ipolevoy** [comment]
@juanep1711 you are confusing ActiveJDBC models and ActiveWeb controllers. Here is a simple app similar to the app in the video example: https://github.com/javalite/activeweb-simple
