### ISSUE TITLE
Fileupload bug in version 2.3

### ISSUE THREAD

**Issue by jacktang** [javalite/activeweb#440]
In activeweb 2.3, general form item (not file) will be ignored in multi-part form.

**Comment by ipolevoy** [comment]
@jacktang can you please provide steps to reproduce?

**Comment by ipolevoy** [comment]
@jacktang , please see http://javalite.io/controllers#uploading-files. 
If you do this in the controller: 

```
 List<FormItem> items = multipartFormItems();
```
and iterate over `items`, you will get all your parameters in the form.

**Comment by ipolevoy** [comment]
Here is an example: https://github.com/javalite/kitchensink/blob/master/src/main/java/app/controllers/UploadController.java

**Comment by jacktang** [comment]
@ipolevoy, I used 
```
Iterator<FormItem> items = uploadedFiles(); 
```
and could not get general form items.  And 

```
List<FormItem> items = multipartFormItems();
```
works like a charm. Thanks!

**Comment by ipolevoy** [comment]
the `uploadedFiles()` gives you files, according to its name :+1:
