### ISSUE TITLE
Missing functionality in AppIntegrationSpec

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#45]
_Original author: ipolevoy@gmail.com (July 10, 2011 04:36:20)_

While it is possible to execute any controller/action, it is impossible to 
add parameters as a query string 
This would be pretty nice:

controller(&quot;blah&quot;).queryString(&quot;name=value&amp;name1=value1&quot;)....

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=45_

**Comment by ipolevoy** [comment]
it is possible to do now, of course
