### ISSUE TITLE
Add ability to turn transaction support during tests

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#47]
_Original author: ipolevoy@gmail.com (July 15, 2011 16:03:43)_

in some cases, the tested code needs to operate transactions. ActiveWeb default behavior gets in the way, and there is no way to turn it off. 

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=47_

**Comment by ipolevoy** [comment]
already implemented https://github.com/javalite/javalite/blob/e91ebdd1e4958bc0965d7ee99e6b7debc59a7b85/activejdbc/src/main/java/org/javalite/activejdbc/test/DBSpec.java#L65
