### ISSUE TITLE
render(String, Map) requires an absolute file path, and it should not

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#50]
_Original author: kamilsk...@gmail.com (August 08, 2011 18:42:29)_

<b>What steps will reproduce the problem?</b>
1.render(&quot;activity_content&quot;).noLayout(); //this works
2.render(&quot;activity_content&quot;, new HashMap()).noLayout(); //this all of the sudden breaks with FileNotFound exception

We expect the render(String, Map) to act the same way as render(String) does so if i decide to add a map to my previous render() method then nothing should break.

<b>What version of the product are you using? On what operating system?</b>
1.1

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=50_

**Comment by ipolevoy** [comment]
this does not produce an exception anymore, closing
