### ISSUE TITLE
Filter's members are not injected when filter applied to specific action

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#54]
_Original author: vasyal...@gmail.com (August 12, 2011 13:56:08)_

When adding filter for specific action, e.g. 
add(new MyFilter()).to(MyController.class).forActions(&quot;index&quot;);
members of filter are not Guice-injected.

ControllerRegistry, lines 86-91: 

  for (String key : metaDataMap.keySet()) {
    ControllerMetaData controllerMetaData = metaDataMap.get(key);
    for (ControllerFilter filter : controllerMetaData.getFilters()) {
      injector.injectMembers(filter);
    }
  }

Here ControllerMetaData returns only filters that are applied to the whole controller. Specific action filters are not returned, hence members for them are not injected.

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=54_

**Comment by ipolevoy** [comment]
all filters are injected, this is really old
