### ISSUE TITLE
Allow fine-grained control of transactions in specs

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#79]
_Original author: ipole...@groupon.com (January 30, 2012 18:32:12)_

Currently you can turn rollback for all test in the project, but this is limiting.
It is far better to  be able to turn opff transaction rollback by framework for specific tests, that need to manipulate transactions. 

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=79_

**Comment by ipolevoy** [comment]
you can  now do it in individual tests: https://github.com/javalite/javalite/blob/e91ebdd1e4958bc0965d7ee99e6b7debc59a7b85/activejdbc/src/main/java/org/javalite/activejdbc/test/DBSpec.java#L90
