### ISSUE TITLE
Remove erroneous log statement: WARN ParamCopy - found 'session' value set by controlle

### ISSUE THREAD

**Issue by artdaw** [javalite/activeweb#8]
_Original author: ipolevoy@gmail.com (April 16, 2011 06:04:57)_

WARN ParamCopy - found 'session' value set by controller. It is reserved by ActiveWeb and will be overwritten

this needs to be investigated, this shows up in logs when session is not set in controller

_Original issue: http://code.google.com/p/activeweb/issues/detail?id=8_

**Comment by ipolevoy** [comment]
not relevant
